version: "3.7"
services:
  validator-create-account:
    container_name: validator-create-account
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_DOCKER_TAG}
    command:
      - "accounts create"
      - "--keystore-path=/data"
      - "--password=${CREATE_ACCOUNT_PASSWORD}"
    volumes:
      - ./validator:/data
