version: "3.7"
services:
  validator-create-account:
    container_name: validator-create-account
    image: gcr.io/prysmaticlabs/prysm/validator:${IMAGE_VERSION_TAG}
    command: accounts create --keystore-path=/data
    volumes:
      - ./validator:/data
