version: "3.7"
services:
  beacon:
    container_name: beacon-chain
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:${IMAGE_VERSION_TAG}
    restart: always
    hostname: beacon-chain
    command:
      - "--datadir=/data"
      - "--p2p-host-ip=${PUBLIC_IP}"
      - "--p2p-host-dns=${PUBLIC_HOST_DNS}"
      - "--p2p-tcp-port=${PUBLIC_TCP_PORT}"
    ports:
      - ${PUBLIC_TCP_PORT}:13000
      - 12000:12000/udp
    volumes:
      - ./beacon:/data
    tty: true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"

  validator:
    container_name: validator
    image: gcr.io/prysmaticlabs/prysm/validator:${IMAGE_VERSION_TAG}
    restart: on-failure
    hostname: validator
    depends_on:
      - beacon
    command:
      - "--beacon-rpc-provider=beacon:4000"
      - "--keymanager=keystore"
      - "--keymanageropts=/data/keystore.json"
      - "--enable-account-metrics"
      - "--graffit=${GRAFFITI}"
    volumes:
      - ./validator:/data
    tty: true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"

  slasher:
    container_name: slasher
    image: gcr.io/prysmaticlabs/prysm/slasher:${IMAGE_VERSION_TAG}
    restart: always
    hostname: slasher
    depends_on:
      - beacon
    command:
      - "--beacon-rpc-provider=beacon:4000"
      - "--datadir=/data"
    volumes:
      - ./slasher:/data
    tty: true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: on-failure
    hostname: prometheus
    command:
      - "--storage.tsdb.retention.time=31d"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"

  grafana:
    container_name: grafana
    image: grafana/grafana:7.0.0
    restart: on-failure
    hostname: grafana
    depends_on:
      - prometheus
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"
