version: "3.7"

x-disabled-service: &disabled-service
  image: tianon/true
  restart: "no"
  command: ""
  entrypoint: ""

services:
  slasher:
    <<: *disabled-service
  prometheus:
    <<: *disabled-service
  grafana:
    <<: *disabled-service
