############################################################
##
## Read up on parameters on
## https://docs.prylabs.network/docs/prysm-usage/parameters/
##
############################################################

graffiti: ""

##############
# Connectivity
beacon-rpc-provider: beacon:4000

#####################################
# Validator accounts & key management
keymanager: wallet
keymanageropts: /data/keystoreWallet.json
