---
# playbook.yml
- name: Provision Image
  hosts: default
  become: true

  tasks:
    - name: Get Vars
      include_vars:
        file: vars.yml

    - name: install git
      apt:
        name: git
        state: present

    - name: remove pre-existing docker installs
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: setup for installing over HTTPS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes
        state: present

    - name: get Docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: "{{ docker.gpg_key_id }}"
        state: present

    - name: setup stable Docker repo
      apt_repository:
        repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        state: present

    - name: install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: present

    - name: enable Docker systemd service
      service:
        name: docker
        state: started
        enabled: yes

    - name: add user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: get docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose.version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: a+x

    - name: upgrade all packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: remove useless package files and dangling dependencies
      apt:
        autoclean: yes
        autoremove: yes
