---
# playbook.yml
- name: Provision Image
  hosts: default
  become: true

  tasks:
    - name: install git
      apt:
        name: git
        state: present

    - name: remove pre-existing docker installs
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: setup for installing over HTTPS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes
        state: present

    - name: get Docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present

    - name: get distro codename
      shell: lsb_release -cs
      register: distro_codename

    - name: setup stable Docker repo
      apt_repository:
        repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        state: present

    - name: install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: present

    - name: enable Docker systemd service
      service:
        name: docker
        state: started
        enabled: yes

    - name: add users to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: remove useless package files and dangling dependencies
      apt:
        autoclean: yes
        autoremove: yes
