# Check files
name: CI

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker Compose Lint
        run: docker-compose config --quiet

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v1
